<a href="https://colab.research.google.com/github/andrewkallai/MLTSA_AKallai/blob/main/python_bootcamp_MLSTA25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [374]:
my_str = "hello"

In [375]:
my_str

'hello'

In [376]:
print(my_str)

hello


In [377]:
my_int = 6

In [378]:
my_float = 6.

In [379]:
print(my_float)

6.0


In [380]:
my_int * my_float

36.0

In [381]:
my_int * my_str

'hellohellohellohellohellohello'

In [382]:
helloworld = "Hello" + "World!"

In [383]:
import numpy as np

In [384]:
my_nparr = np.array([1,2,3])

In [385]:
my_int * my_nparr

array([ 6, 12, 18])

In [386]:
my_bool = True

In [387]:
my_int = 1

In [388]:
my_int != 6

True

In [389]:
if my_int != 6:
  print("my_int is not 6")
else:
  print("it was 6!!")

my_int is not 6


In [390]:
type(my_int)

int

In [391]:
my_nparr.dtype

dtype('int64')

In [392]:
my_nparr.max()

3

In [393]:
my_nparr.argmax()

2

In [394]:
my_nparr

array([1, 2, 3])

In [395]:
my_nparr

array([1, 2, 3])

In [396]:
my_nparr[0]

1

In [397]:
my_nparr[2]

3

In [398]:
my_nparr[-1]

3

In [399]:
my_nparr[1:]

array([2, 3])

In [400]:
my_nparr[1:2]

array([2])

In [401]:
my_nparr[1:3]

array([2, 3])

In [402]:
list(range(1,4))

[1, 2, 3]

In [403]:
for a in range(1, 4):
  print(sum(np.arange(0,a)))

0
1
3


In [404]:
np.arange(0,a)

array([0, 1, 2])

In [405]:
def allodds(lastn):
  """
  prints odd numbers
  Input:
    lastn: (int) last number in the list
  Return:
    a list of odd numbers
  """
  odds = []
  for a in range(0, lastn + 1):
    if a % 2 == 1:
      odds.append(a)
    #print(odds)
  return odds


In [406]:
allodds?

In [407]:
allodds(10)

[1, 3, 5, 7, 9]

In [408]:
def check_str(s):
  """
  This function expects a string and checks if it is a palindrome.
  """
  assert type(s) == str, "is not a string"
  if s[::-1].lower() == s.lower():
      return True
  return False

In [409]:
print(check_str("talha"))

False


In [410]:
print(check_str("tacocat"))

True


In [411]:
print(check_str("racecar"))

True
